import os
import json
from dotenv import load_dotenv
load_dotenv()

from langchain_openai import ChatOpenAI
from langsmith import traceable, tracing_context

# --- 1. Define a Core Data Search Tool designed to intentionally fail once ---
call_counter = 0

def search(query: str) -> str:
    """Useful for searching the historical brewing archives."""
    global call_counter
    call_counter += 1
    
    print(f"\n[TOOL ATTEMPT {call_counter}] Running archive lookup for: '{query}'")
    
    # Intentionally crash on the first run to simulate a network database timeout error
    if call_counter == 1:
        print("-> [FAULT DETECTED] Simulating an internal database timeout!")
        raise RuntimeError("Database connection timed out. System retry required.")
        
    # Succeed cleanly on the next attempt
    return f"Search successful for: {query}. Key Insight: Stout requires 10% roasted barley."

# --- 2. Initialize the Infrastructure Layer ---
LM_STUDIO_BASE_URL = os.getenv("LM_STUDIO_BASE_URL", "http://localhost:1234/v1")
LM_STUDIO_API_KEY = os.getenv("LM_STUDIO_API_KEY", "lm-studio")
LM_STUDIO_MODEL = os.getenv("LM_STUDIO_MODEL", "qwen2.5-coder-1.5b-instruct")

local_llm = ChatOpenAI(
    base_url=LM_STUDIO_BASE_URL,
    api_key=LM_STUDIO_API_KEY,
    model=LM_STUDIO_MODEL,
    temperature=0.0,  # Zero configuration stops text formatting variance leaks
    timeout=600,
)

# --- 3. Custom Fault-Tolerant Execution Wrapper Engine ---
@traceable(run_type="chain", name="ResilientToolExecutionEngine")
def execute_tool_with_retry(search_query: str, max_retries: int = 2) -> str:
    """Simulates ToolRetryMiddleware behavior by programmatically managing fault tolerance loops."""
    retries = 0
    while retries < max_retries:
        try:
            # Attempt to execute the Python tool function logic
            result = search(search_query)
            return result
        except Exception as tool_error:
            retries += 1
            print(f"-> [RETRY MIDDLEWARE] Caught error: '{tool_error}'. Attempting retry {retries}/{max_retries}...")
            
    raise RuntimeError(f"Tool failed permanently after {max_retries} attempts.")

# --- 4. Build Parent Instructions ---
SYSTEM_PROMPT = (
    "You are the Lead Master Brewer and Architect Agent.\n\n"
    "CRITICAL INSTUCTION:\n"
    "You must declare which tool you want to use using a raw JSON snippet format.\n"
    "Output exactly this layout, replacing the bracketed value:\n"
    '{"name": "search", "arguments": {"query": "<insert search parameters here>"}}\n'
    "Do not include conversational preamble or extra text."
)

# --- 5. Run Execution Loop inside Tracing Context ---
test_prompt = "Search the archive for stout techniques and summarize the results."

with tracing_context(
    project_name="agent-fault-tolerance",
    tags=["qwen-coder-tier", "resilience-evaluation"]
):
    print("==================================================")
    print(f"Executing Fault Tolerance Sandbox via {LM_STUDIO_MODEL}...")
    print("==================================================")
    
    try:
        # Step 1: Let the model evaluate the prompt guidelines and emit its JSON intent string
        response = local_llm.invoke(f"{SYSTEM_PROMPT}\n\nUser Question: {test_prompt}")
        raw_output = response.content
        print(f"\n[PARENT PROCESSOR LOG] Raw string received:\n{raw_output}")
        
        # Step 2: Clean out the code block markdown symbols generated by the Coder parameter weights
        clean_json = raw_output.replace("```json", "").replace("```", "").strip()
        parsed_action = json.loads(clean_json)
        target_query = parsed_action["arguments"]["query"]
        
        # Step 3: Run the workflow inside our custom resilient fault-tolerant execution function
        database_facts = execute_tool_with_retry(target_query, max_retries=2)
        
        # Step 4: Feed the successful result back to the model to generate the final clear summary text
        synthesis_prompt = (
            f"You are the Lead Master Brewer. Here are the accurate facts retrieved from the database:\n"
            f"'{database_facts}'\n\n"
            f"Based on these exact facts, write a concise single-sentence summary layout for the user."
        )
        
        final_answer = local_llm.invoke(synthesis_prompt)
        
        print("\n================ FINAL ARCHITECT RESILIENT OUTPUT ================")
        print(final_answer.content)
        print("==================================================================")
        
    except Exception as e:
        print(f"Error during sandbox planning run execution loop: {e}")
